In [3]:
import numpy as np

# 加载文件
data = np.load("D:\MyWork\Program\BrainVis\可视化系统\SEED-DV\Video\meta-info\All_video_optical_flow_score.npy")

print(f"Shape: {data.shape}")
print(f"Number of elements: {data.size}")
print(f"Data type: {data.dtype}")


Shape: (7, 200)
Number of elements: 1400
Data type: float64


In [4]:
print(data)

[[6.15113964 3.61656577 6.1460275  ... 1.11590138 0.32528771 3.13943273]
 [1.69042687 1.51693096 0.84057592 ... 0.43405012 0.65484254 2.28020846]
 [0.96534792 2.31613423 3.59078644 ... 0.91264231 2.00174276 1.68722032]
 ...
 [1.86760979 2.28685878 2.58938373 ... 0.88423651 5.22219776 6.22558072]
 [0.20841334 0.57574575 0.51481974 ... 0.91469667 0.80459707 0.32417185]
 [0.50148895 0.18683513 0.2369235  ... 2.4265361  1.43077375 0.4518423 ]]


### 提取第一个视频段的OF

In [6]:
OF1 = data[0,:]
print(OF1.shape)

(200,)


In [9]:
import json
OF1_list = OF1.tolist()
with open("../../SEED-DV/single-channel/OF_Processed/OF1.json", "w") as f:
    json.dump(OF1_list, f)